# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "656470eec397396e68d2730676de1db5"
name = "nps-form-arzz"
handle = "nps-form-arzz"
application_url = "https://gzip-hats-cottages-champagne.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "arzz-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_metaobjects,read_orders,write_customers,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [
  "https://gzip-hats-cottages-champagne.trycloudflare.com/auth/callback",
  "https://gzip-hats-cottages-champagne.trycloudflare.com/auth/shopify/callback",
  "https://gzip-hats-cottages-champagne.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://gzip-hats-cottages-champagne.trycloudflare.com"
subpath = "arzz-form"
prefix = "apps"

[pos]
embedded = false
